// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum DivicePlatform

// 设备平台
typedef GPB_ENUM(DivicePlatform) {
  DivicePlatform_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  DivicePlatform_InvalidDp = 0,
  DivicePlatform_AndroidDp = 1,
  DivicePlatform_IosDp = 2,
  DivicePlatform_WebDp = 3,
};

GPBEnumDescriptor *DivicePlatform_EnumDescriptor(void);

BOOL DivicePlatform_IsValidValue(int32_t value);

#pragma mark - Enum ShareChannel

// 分享平台
typedef GPB_ENUM(ShareChannel) {
  ShareChannel_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ShareChannel_InvalidSc = 0,
  ShareChannel_WeiboSc = 1,
  ShareChannel_WeixinSc = 2,
  ShareChannel_PengyouquanSc = 3,
  ShareChannel_QqSc = 4,
};

GPBEnumDescriptor *ShareChannel_EnumDescriptor(void);

BOOL ShareChannel_IsValidValue(int32_t value);

#pragma mark - CommonRoot

@interface CommonRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - NullRpcRequest

// empty rpc request
@interface NullRpcRequest : GPBMessage

@end

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_Code = 1,
  Response_FieldNumber_Msg = 2,
  Response_FieldNumber_Desc = 3,
};

// sample rpc response
@interface Response : GPBMessage

@property(nonatomic, readwrite) int64_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msg;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

@end

#pragma mark - AppConfig

typedef GPB_ENUM(AppConfig_FieldNumber) {
  AppConfig_FieldNumber_AppId = 1,
  AppConfig_FieldNumber_AppName = 2,
  AppConfig_FieldNumber_Key = 3,
  AppConfig_FieldNumber_LoginTokenDuration = 4,
};

@interface AppConfig : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite) int64_t loginTokenDuration;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
