// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.app.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Response;
@class User;
@class UserAddress;
GPB_ENUM_FWD_DECLARE(UserSex);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ChangePasswordType

typedef GPB_ENUM(ChangePasswordType) {
  ChangePasswordType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ChangePasswordType_ChangePassword = 0,
  ChangePasswordType_ForgetPassword = 1,
};

GPBEnumDescriptor *ChangePasswordType_EnumDescriptor(void);

BOOL ChangePasswordType_IsValidValue(int32_t value);

#pragma mark - UserAppRoot

@interface UserAppRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - GetUserAddrParam

typedef GPB_ENUM(GetUserAddrParam_FieldNumber) {
  GetUserAddrParam_FieldNumber_AddrId = 1,
};

@interface GetUserAddrParam : GPBMessage

@property(nonatomic, readwrite) int64_t addrId;

@end

#pragma mark - GetUserAddrResp

typedef GPB_ENUM(GetUserAddrResp_FieldNumber) {
  GetUserAddrResp_FieldNumber_Resp = 1,
  GetUserAddrResp_FieldNumber_Addr = 2,
};

@interface GetUserAddrResp : GPBMessage

@property(nonatomic, readwrite) BOOL hasResp;
@property(nonatomic, readwrite, strong, null_resettable) Response *resp;

@property(nonatomic, readwrite) BOOL hasAddr;
@property(nonatomic, readwrite, strong, null_resettable) UserAddress *addr;

@end

#pragma mark - DelUserAddrParam

typedef GPB_ENUM(DelUserAddrParam_FieldNumber) {
  DelUserAddrParam_FieldNumber_Token = 1,
  DelUserAddrParam_FieldNumber_AddrIdsArray = 2,
};

// 删除用户地址参数列表
@interface DelUserAddrParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *addrIdsArray;
@property(nonatomic, readonly) NSUInteger addrIdsArray_Count;

@end

#pragma mark - UpdateUserAddrsParam

typedef GPB_ENUM(UpdateUserAddrsParam_FieldNumber) {
  UpdateUserAddrsParam_FieldNumber_Token = 1,
  UpdateUserAddrsParam_FieldNumber_AddrsArray = 2,
};

// 更新用户地址参数列表
@interface UpdateUserAddrsParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

// |addrsArray| contains |UserAddress|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *addrsArray;
@property(nonatomic, readonly) NSUInteger addrsArray_Count;

@end

#pragma mark - ChangeUserSexParam

typedef GPB_ENUM(ChangeUserSexParam_FieldNumber) {
  ChangeUserSexParam_FieldNumber_Token = 1,
  ChangeUserSexParam_FieldNumber_Sex = 2,
};

// 更新用户性别参数列表
@interface ChangeUserSexParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite) enum UserSex sex;

@end

int32_t ChangeUserSexParam_Sex_RawValue(ChangeUserSexParam *message);
void SetChangeUserSexParam_Sex_RawValue(ChangeUserSexParam *message, int32_t value);

#pragma mark - GetUserParam

typedef GPB_ENUM(GetUserParam_FieldNumber) {
  GetUserParam_FieldNumber_HongId = 1,
};

@interface GetUserParam : GPBMessage

@property(nonatomic, readwrite) uint64_t hongId;

@end

#pragma mark - GetUserResp

typedef GPB_ENUM(GetUserResp_FieldNumber) {
  GetUserResp_FieldNumber_Resp = 1,
  GetUserResp_FieldNumber_User = 2,
};

@interface GetUserResp : GPBMessage

@property(nonatomic, readwrite) BOOL hasResp;
@property(nonatomic, readwrite, strong, null_resettable) Response *resp;

@property(nonatomic, readwrite) BOOL hasUser;
@property(nonatomic, readwrite, strong, null_resettable) User *user;

@end

#pragma mark - NewUserAddrParam

typedef GPB_ENUM(NewUserAddrParam_FieldNumber) {
  NewUserAddrParam_FieldNumber_Token = 1,
  NewUserAddrParam_FieldNumber_Name = 2,
  NewUserAddrParam_FieldNumber_Contact = 3,
  NewUserAddrParam_FieldNumber_Area = 4,
  NewUserAddrParam_FieldNumber_Detail = 5,
};

@interface NewUserAddrParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contact;

@property(nonatomic, readwrite, copy, null_resettable) NSString *area;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detail;

@end

#pragma mark - NewUserAddrResp

typedef GPB_ENUM(NewUserAddrResp_FieldNumber) {
  NewUserAddrResp_FieldNumber_Resp = 1,
  NewUserAddrResp_FieldNumber_Addr = 2,
};

@interface NewUserAddrResp : GPBMessage

@property(nonatomic, readwrite) BOOL hasResp;
@property(nonatomic, readwrite, strong, null_resettable) Response *resp;

@property(nonatomic, readwrite) BOOL hasAddr;
@property(nonatomic, readwrite, strong, null_resettable) UserAddress *addr;

@end

#pragma mark - ChangePasswordParam

typedef GPB_ENUM(ChangePasswordParam_FieldNumber) {
  ChangePasswordParam_FieldNumber_Token = 1,
  ChangePasswordParam_FieldNumber_PasswordOld = 2,
  ChangePasswordParam_FieldNumber_PasswordNew = 3,
};

// 修改密码参数
@interface ChangePasswordParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordOld;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordNew;

@end

#pragma mark - ForgetPasswordParam

typedef GPB_ENUM(ForgetPasswordParam_FieldNumber) {
  ForgetPasswordParam_FieldNumber_HongId = 1,
  ForgetPasswordParam_FieldNumber_PasswordNew = 2,
};

// 忘记密码参数
@interface ForgetPasswordParam : GPBMessage

@property(nonatomic, readwrite) uint64_t hongId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordNew;

@end

#pragma mark - ChangeUserAvatarParam

typedef GPB_ENUM(ChangeUserAvatarParam_FieldNumber) {
  ChangeUserAvatarParam_FieldNumber_Token = 1,
  ChangeUserAvatarParam_FieldNumber_Avatar = 2,
};

@interface ChangeUserAvatarParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - ChangeUserNickParam

typedef GPB_ENUM(ChangeUserNickParam_FieldNumber) {
  ChangeUserNickParam_FieldNumber_Token = 1,
  ChangeUserNickParam_FieldNumber_Nick = 2,
};

@interface ChangeUserNickParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nick;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
