// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.pingpp.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Response;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserPingppRoot

@interface UserPingppRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PingppChargeParam

typedef GPB_ENUM(PingppChargeParam_FieldNumber) {
  PingppChargeParam_FieldNumber_AppId = 1,
  PingppChargeParam_FieldNumber_OrderId = 2,
  PingppChargeParam_FieldNumber_Channel = 3,
  PingppChargeParam_FieldNumber_Subject = 4,
  PingppChargeParam_FieldNumber_Body = 5,
  PingppChargeParam_FieldNumber_Amount = 6,
  PingppChargeParam_FieldNumber_Token = 7,
};

@interface PingppChargeParam : GPBMessage

// 哪个app
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

// 订单号
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

// 渠道，参考ping++文档
@property(nonatomic, readwrite, copy, null_resettable) NSString *channel;

// 订单标题
@property(nonatomic, readwrite, copy, null_resettable) NSString *subject;

// 订单内容
@property(nonatomic, readwrite, copy, null_resettable) NSString *body;

// 订单总额
@property(nonatomic, readwrite) uint64_t amount;

// 用户登陆token
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - PingppChargeResp

typedef GPB_ENUM(PingppChargeResp_FieldNumber) {
  PingppChargeResp_FieldNumber_Resp = 1,
  PingppChargeResp_FieldNumber_Charge = 2,
};

@interface PingppChargeResp : GPBMessage

@property(nonatomic, readwrite) BOOL hasResp;
@property(nonatomic, readwrite, strong, null_resettable) Response *resp;

// charge对象json化后的string，客户端操作请参考ping++的客户端sdk
@property(nonatomic, readwrite, copy, null_resettable) NSString *charge;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
